"""
This is the working graph for Intergalactic Federation.

It allows us to declare characters and quests and stories and
create a graph out of it that we can then work with.

It should be noted that the layers go Storyline is made of Quests
and Quests are made of Objectives. All three of those can contain

"""