"""
Ideas
https://youtu.be/HEhhWL1oUTM use socketio for groundstation stuff
cube https://robohub.org/the-one-wheel-cubli/
graphics project https://fgiesen.wordpress.com/2011/07/09/a-trip-through-the-graphics-pipeline-2011-index/

"""