deps:
  astropy:
  numpy:
  pyYAML:
  jplephem:
  packaging:
    version :  "21.0"
  pyerfa:
  progress:
  pyparsing:
  jupyterlab:
    version: "v4.1.0b0"
  matplotlib:
  dropbox:
  schedule:
  fastapi:
    no_notebooks: true
  uvicorn[standard]:
    no_notebooks: true
  redis:
    no_notebooks: true
  pyaudio:
    no_notebooks: true
  confluent-kafka:
  cbor2:
  discord.py:
