services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: good_work_postgres
    restart: always
    environment:
      POSTGRES_USER: clatham      # Replace with your desired username
      POSTGRES_PASSWORD: admin # Replace with your desired password
      POSTGRES_DB: good_work           # Replace with your desired database name
    ports:
      - "5432:5432" # Exposes PostgreSQL to your host machine on port 5432
    volumes:
      - good_work_postgres_data:/var/lib/postgresql/data
    networks:
      - good_work_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clatham -d good_work"] # Use your actual user and db
      interval: 10s
      timeout: 5s
      retries: 5
  # fastapi:
  #   image: TODO
  #   container_name: good_work_fastapi
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   # volumes:
  #   networks:
  #     - good_work_network
  #   # healthcheck:


volumes:
  good_work_postgres_data: # Defines a named volume for PostgreSQL data persistence

networks:
  good_work_network:   # Defines a custom bridge network for services to communicate
    driver: bridge