load("//tools/python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "application",
    srcs = ["application.py"],
    deps = [
        "//tools/python/log",
        "//tools/python/sentry",
    ],
)