[package]
name = "pm"
version = "0.1.0"
edition = "2021"

[dependencies]
pm_macros = { path = "../macros" }
mut_cell = { path = "../mut_cell" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
