[dependencies]
[eyre]
version= "0.6.8"
    },
    "env_logger": {
        "version": "=0.10.0",
    },
    "log": {
        "version": "=0.4.20",
    },
    "uuid": {
        "features": [
            "v4",
        ],
        "version": "=1.4.1",
    },
    "kafka": {
        "version": "=0.9",
    },
    "clap": {
        "version": "=4.4.1",
        "features": ["derive"],
    },
    "tokio": {
        "version": "=1.32.0",
        "features": ["full"],
    },
    "arrayvec": {
        "version": "0.7.4",
    },
    "proc-macro2": {
        "version": "1.0.66",
    },