on:
  push:
    branches:
      - main
jobs:
  ci_job:
    name: ci
    runs-on: self-hosted
    steps:
      - name: install bazelisk
        run: ../../provision/install_bazelisk.sh
        shell: bash
        
      
