on:
  pull_request:
    branches:
      - main
      - 'releases/**'
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  ci_job:
    name: ci
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
      - name: Test all targets
        run: bazel test -- //... -//z_practice/... -//third_party/python/...


