on:
  push:
    branches:
      - main
jobs:
  ci_job:
    name: ci
    runs-on: ubuntu-18.04
    steps:
      - name: install bazelisk
        run: provision/install_bazelisk.sh
        shell: bash
        
      
