on:
  push:
    branches:
      - main
jobs:
  ci_job:
    name: ci
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
      - name: install bazelisk
        run: bazel test //...
        shell: bash
        
      
