on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    ci_job:
        name: ci
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@vv4.1.1
            - name: Setup Bazelisk
              uses: bazelbuild/setup-bazelisk@v2.0.0
            - name: Test all targets
              run: bazel test //...
